

MANUAL = 0
AUTO = 1

CMD = {"MIN_YAW": 0,
       "PLUS_YAW": 1,
       "MIN_PITCH": 2,
       "PLUS_PITCH": 3,
       "MIN_ROLL": 4,
       "PLUS_ROLL": 5,
       "HOME": 6,
       "ENABLE": 7,
       "DISABLE": 8}

MAX_SPEED = 30

YAW_HOME = 2048
PITCH_HOME = 2800
ROLL_HOME = 3072
RANGE = 1024

YAW = [YAW_HOME-RANGE, YAW_HOME+RANGE]
PITCH = [PITCH_HOME-RANGE, PITCH_HOME+RANGE]
ROLL = [ROLL_HOME-RANGE, ROLL_HOME+RANGE]

STEP = RANGE//180