

MANUAL = 0
AUTO = 1

YAW_HOME = 3072
PITCH_HOME = 650
ROLL_HOME = 3072
HOME = [YAW_HOME, PITCH_HOME, ROLL_HOME]

RANGE = 2048

YAW = [YAW_HOME-(RANGE/2), YAW_HOME+(RANGE/2)]
PITCH = [PITCH_HOME-(RANGE/2), PITCH_HOME+(RANGE/2)]
ROLL = [ROLL_HOME-(RANGE/2), ROLL_HOME+(RANGE/2)]

STEP = RANGE//180
